<article class="BottomBlocks-mainContainer">
    <div class="BottomBlocks-card">
        <h3 class="BottomBlocks-title"><?= __('Prekių gidai') ?></h3>
        <div class="BottomBlocks-content">
            <div class="BottomBlocks-descriptionContainer">
                <img class="BottomBlocks-icon" src="<?= $block->getViewFileUrl('images/icons/bottom-block/1.svg') ?>" alt="<?= __('Prekių gidai') ?>">
                <p class="BottomBlocks-description"><?= __('Sužinokite, kaip išsirinkti tinkamiausią prekę.') ?></p>
            </div>
            <a class="BottomBlocks-actionButton" href="#">
                <?= __('Plačiau') ?>
                <img src="<?= $block->getViewFileUrl('images/icons/bottom-block/arrow.svg') ?>" alt="<?= __('read more') ?>">
            </a>
        </div>
    </div>
    <div class="BottomBlocks-card">
        <h3 class="BottomBlocks-title"><?= __('Nemokamas atsiėmimas') ?></h3>
        <div class="BottomBlocks-content">
            <div class="BottomBlocks-descriptionContainer">
                <img class="BottomBlocks-icon" src="<?= $block->getViewFileUrl('images/icons/bottom-block/2.svg') ?>" alt="<?= __('Nemokamas atsiėmimas') ?>">
                <p class="BottomBlocks-description"><?= __('Užsakymą atsiimkite viename iš TOPO CENTRO užsakymų atsiėmimo centrų.') ?></p>
            </div>
            <a class="BottomBlocks-actionButton" href="#">
                <?= __('Plačiau') ?>
                <img src="<?= $block->getViewFileUrl('images/icons/bottom-block/arrow.svg') ?>" alt="<?= __('read more') ?>">
            </a>
        </div>
    </div>
    <div class="BottomBlocks-card">
        <h3 class="BottomBlocks-title"><?= __('Paslaugos') ?></h3>
        <div class="BottomBlocks-content">
            <div class="BottomBlocks-descriptionContainer">
                <img class="BottomBlocks-icon" src="<?= $block->getViewFileUrl('images/icons/bottom-block/3.svg') ?>" alt="<?= __('Paslaugos') ?>">
                <p class="BottomBlocks-description"><?= __('Susipažinkite su TOPO CENTRAS teikiamomis paslaugomis.') ?></p>
            </div>
            <a class="BottomBlocks-actionButton" href="#">
                <?= __('Plačiau') ?>
                <img src="<?= $block->getViewFileUrl('images/icons/bottom-block/arrow.svg') ?>" alt="<?= __('read more') ?>">
            </a>
        </div>
    </div>
    <div class="BottomBlocks-card">
        <h3 class="BottomBlocks-title"><?= __('Kaip apsipirkti?') ?></h3>
        <div class="BottomBlocks-content">
            <div class="BottomBlocks-descriptionContainer">
                <img class="BottomBlocks-icon" src="<?= $block->getViewFileUrl('images/icons/bottom-block/4.svg') ?>" alt="<?= __('Kaip apsipirkti?') ?>">
                <p class="BottomBlocks-description"><?= __('Sužinokite, kaip apsipirkti www.topocentras.lt.') ?></p>
            </div>
            <a class="BottomBlocks-actionButton" href="#">
                <?= __('Plačiau') ?>
                <img src="<?= $block->getViewFileUrl('images/icons/bottom-block/arrow.svg') ?>" alt="<?= __('read more') ?>">
            </a>
        </div>
    </div>
</article>
