<div class="imagesContainer-desk">
    <div class="categories-slider-wrapper">
        <div class="categories-container">
            <a class="category-link" href="#">
                <div class="category-image-wrapper">
                    <img src="<?= $block->getUrl('media') ?>topocentras/category-slider/slide-1.jpg" alt="<?= __('Išmanieji telefonai') ?>">
                </div>
                <p class="category-title-t"><?= __('Išmanieji telefonai') ?></p>
            </a>
            <a class="category-link" href="#">
                <div class="category-image-wrapper">
                    <img src="<?= $block->getUrl('media') ?>topocentras/category-slider/slide-2.jpg" alt="<?= __('Televizoriai') ?>">
                </div>
                <p class="category-title-t"><?= __('Televizoriai') ?></p>
            </a>
            <a class="category-link" href="#">
                <div class="category-image-wrapper">
                    <img src="<?= $block->getUrl('media') ?>topocentras/category-slider/slide-3.jpg" alt="<?= __('Nešiojami kompiuteriai') ?>">
                </div>
                <p class="category-title-t"><?= __('Nešiojami kompiuteriai') ?></p>
            </a>
            <a class="category-link" href="#">
                <div class="category-image-wrapper">
                    <img src="<?= $block->getUrl('media') ?>topocentras/category-slider/slide-4.jpg" alt="<?= __('Ausinės') ?>">
                </div>
                <p class="category-title-t"><?= __('Ausinės') ?></p>
            </a>
            <a class="category-link" href="#">
                <div class="category-image-wrapper">
                    <img src="<?= $block->getUrl('media') ?>topocentras/category-slider/slide-5.jpg" alt="<?= __('PlayStation 5 žaidimų konsolės') ?>">
                </div>
                <p class="category-title-t"><?= __('PlayStation 5 žaidimų konsolės') ?></p>
            </a>
            <a class="category-link" href="#">
                <div class="category-image-wrapper">
                    <img src="<?= $block->getUrl('media') ?>topocentras/category-slider/slide-6.png" alt="<?= __('Išmanieji laikrodžiai') ?>">
                </div>
                <p class="category-title-t"><?= __('Išmanieji laikrodžiai') ?></p>
            </a>
            <a class="category-link" href="#">
                <div class="category-image-wrapper">
                    <img src="<?= $block->getUrl('media') ?>topocentras/category-slider/slide-7.jpg" alt="<?= __('Dulkių siurbliai - šluotos') ?>">
                </div>
                <p class="category-title-t"><?= __('Dulkių siurbliai - šluotos') ?></p>
            </a>
        </div>
    </div>
</div>
