<div class="widget block block-static-block">
    <div class="brands-container">
        <a id="brand-apple" class="brands-links" href="#" aria-label="<?= __('Apple prekės') ?>">
            <img src="<?= $block->getUrl('media') ?>topocentras/brands/1-apple.svg" alt="<?= __('Apple logo') ?>">
        </a>
        <a id="brand-miele" class="brands-links" href="#" aria-label="<?= __('Miele prekės') ?>">
            <img src="<?= $block->getUrl('media') ?>topocentras/brands/2-miele.svg" alt="<?= __('Miele logo') ?>">
        </a>
        <a id="brand-dyson" class="brands-links" href="#" aria-label="<?= __('Dyson prekės') ?>">
            <img src="<?= $block->getUrl('media') ?>topocentras/brands/3-dyson.png" alt="<?= __('Dyson logo') ?>">
        </a>
        <a id="brand-jura" class="brands-links" href="#" aria-label="<?= __('Jura prekės') ?>">
            <img src="<?= $block->getUrl('media') ?>topocentras/brands/4-jura.png" alt="<?= __('Jura logo') ?>">
        </a>
        <a id="brand-xiaomi" class="brands-links" href="#" aria-label="<?= __('Xiaomi prekės') ?>">
            <img src="<?= $block->getUrl('media') ?>topocentras/brands/5-mi.png" alt="<?= __('Xiaomi logo') ?>">
        </a>
        <a id="brand-delonghi" class="brands-links" href="#" aria-label="<?= __('DeLonghi prekės') ?>">
            <img src="<?= $block->getUrl('media') ?>topocentras/brands/6-deLonghi.png" alt="<?= __('DeLonghi logo') ?>">
        </a>
        <a id="brand-samsung" class="brands-links" href="#" aria-label="<?= __('Samsung prekės') ?>">
            <img src="<?= $block->getUrl('media') ?>topocentras/brands/7-samsung.svg" alt="<?= __('Samsung logo') ?>">
        </a>
        <a id="brand-omen" class="brands-links" href="#" aria-label="<?= __('Lego prekės') ?>">
            <img src="<?= $block->getUrl('media') ?>topocentras/brands/8-lego.png" alt="<?= __('Lego logo') ?>" height="48" style="width: 48px;">
        </a>
    </div>
</div>
