<?php
$mediaUrl = $block->getUrl('', ['_type' => \Magento\Framework\UrlInterface::URL_TYPE_MEDIA]);
?>
<div id="banner-six-3" class="row slider9 box-container owl-theme owl-carousel">
    <div class="item-wrapper">
        <div class="item">
            <span class="photo">
                <img title="<?php echo __('Išpardavimas | Mobilieji telefonai'); ?>" src="<?php echo $mediaUrl; ?>topocentras/banners/banner-1.jpg" alt="<?php echo __('Išpardavimas | Mobilieji telefonai'); ?>" loading="lazy">
            </span>
            <a class="block-link" href="#"></a>
        </div>
    </div>
    <div class="item-wrapper">
        <div class="item">
            <span class="photo">
                <img title="<?php echo __('Stambi buitinė technika'); ?>" src="<?php echo $mediaUrl; ?>topocentras/banners/banner-2.jpg" alt="<?php echo __('Stambi buitinė technika'); ?>" loading="lazy">
            </span>
            <a class="block-link" href="#"></a>
        </div>
    </div>
    <div class="item-wrapper">
        <div class="item">
            <span class="photo">
                <img title="<?php echo __('Išpardavimas | Televizoriai'); ?>" src="<?php echo $mediaUrl; ?>topocentras/banners/banner-3.jpg" alt="<?php echo __('Išpardavimas | Televizoriai'); ?>" loading="lazy">
            </span>
            <a class="block-link" href="#"></a>
        </div>
    </div>
    <div class="item-wrapper">
        <div class="item">
            <span class="photo">
                <img title="<?php echo __('Šildymo įrenginiams TOP kainos'); ?>" src="<?php echo $mediaUrl; ?>topocentras/banners/banner-4.jpg" alt="<?php echo __('Šildymo įrenginiams TOP kainos'); ?>" loading="lazy">
            </span>
            <a class="block-link" href="#"></a>
        </div>
    </div>
</div>
