<?php
/**
 * Footer Contact Information
 */
?>
<div class="footer-contact-container">
    <div class="footer-menu-toggle">
        <h2 class="footer-menu-title">
            <a href="#"><?= __('Susisiekite') ?></a>
        </h2>
    </div>
    <div class="footer-menu-content">
        <ul class="unstyled">
            <li><?= __('Ekspertų linija - konsultacijos perkantiems') ?></li>
            <li>
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/icons/footer/phoneic.svg')) ?>" alt="" width="15" height="15">
                <a class="phone" href="tel:+37070050052">+370 700 50052</a>
            </li>
            <li>
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/icons/footer/people.svg')) ?>" alt="" width="15" height="15">
                <a class="phone" href="https://formos.topocentras.lt/252401989284364" target="_blank" rel="noopener"><?= __('Nuotolinė konsultacija') ?></a>
            </li>
            <li><br><?= __('Klientų aptarnavimo numeris') ?></li>
            <li>
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/icons/footer/phoneic.svg')) ?>" alt="" width="15" height="15">
                <a class="phone" href="tel:+37066000200">+370 660 00200</a>
            </li>
            <li>
                <a href="mailto:info@topocentras.lt">
                    <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/icons/footer/emailic.svg')) ?>" alt="" width="15" height="15">
                    info@topocentras.lt
                </a>
            </li>
            <li>
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/icons/footer/time.svg')) ?>" alt="" width="15" height="15">
                <?= __('I - V 08:00 - 22:00') ?>
            </li>
            <li>
                <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/icons/footer/time.svg')) ?>" alt="" width="15" height="15">
                <?= __('VI-VII 09:00 - 17:00') ?>
            </li>
        </ul>
    </div>
</div>
