<?php
/**
 * Footer Menu - Purchase Information
 */
?>
<div class="footer-menu">
    <div class="footer-menu-toggle">
        <h2 class="footer-menu-title">
            <a href="#"><?= __('Pirkimo informacija') ?></a>
        </h2>
    </div>
    <div class="footer-menu-content">
        <ul>
            <li><a href="#"><?= __('Mokėjimo būdai') ?></a></li>
            <li><a href="#"><?= __('Pristatymo sąlygos') ?></a></li>
            <li><a href="#"><?= __('Prekių garantija') ?></a></li>
            <li><a href="#"><?= __('Prekių grąžinimas') ?></a></li>
            <li><a href="#"><?= __('Taisyklės') ?></a></li>
            <li><a href="#"><?= __('Privatumo politika') ?></a></li>
            <li><a href="#"><?= __('Kaip pirkti? Video instrukcijos') ?></a></li>
            <li><a href="#"><?= __('Užsakymo informacija') ?></a></li>
            <li><a href="#"><?= __('DUK') ?></a></li>
            <li><a href="#"><?= __('Prekių gidai') ?></a></li>
            <li><a href="#"><?= __('Produktų video apžvalgos') ?></a></li>
        </ul>
    </div>
</div>
