<?php
/**
 * Footer Menu - About Topo Centra
 */
?>
<div class="footer-menu">
    <div class="footer-menu-toggle">
        <h2 class="footer-menu-title">
            <a href="#"><?= __('Apie TOPO CENTRĄ') ?></a>
        </h2>
    </div>
    <div class="footer-menu-content">
        <ul>
            <li><a href="#"><?= __('Apie mus') ?></a></li>
            <li><a href="#"><?= __('Parduotuvių tinklas') ?></a></li>
            <li><a href="#"><?= __('Naujienos, patarimai ir gidai') ?></a></li>
            <li><a href="#"><?= __('Paslaugos') ?></a></li>
            <li><a href="#"><?= __('Prekiniai ženklai') ?></a></li>
            <li><a href="#"><?= __('Dovanų kuponai ir kortelės') ?></a></li>
            <li><a title="TOPO CENTRO naudų programa" href="#"><?= __('TOPO CENTRO naudų programa') ?></a></li>
            <li><a href="#"><?= __('Karjera') ?></a></li>
            <li><a href="#"><?= __('Verslui') ?></a></li>
            <li><a href="#"><?= __('Kontaktai') ?></a></li>
            <li><a href="#"><?= __('Žiniasklaidai') ?></a></li>
        </ul>
    </div>
</div>
