<?php
/**
 * Footer Menu - About Topo Centra
 */
?>
<div class="footer-menu">
    <div class="footer-menu-toggle">
        <h2 class="footer-menu-title">
            <a href="#"><?= __('Apie TOPO CENTRĄ') ?></a>
        </h2>
    </div>
    <div class="footer-menu-content">
        <ul>
            <li><a href="<?= $block->escapeUrl($block->getUrl('imones-informacija')) ?>"><?= __('Apie mus') ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getUrl('parduotuviu-tinklas')) ?>"><?= __('Parduotuvių tinklas') ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getUrl('naujienos')) ?>"><?= __('Naujienos, patarimai ir gidai') ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getUrl('paslaugos')) ?>"><?= __('Paslaugos') ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getUrl('prekiniai-zenklai')) ?>"><?= __('Prekiniai ženklai') ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getUrl('dovanu-kuponas')) ?>"><?= __('Dovanų kuponai ir kortelės') ?></a></li>
            <li><a title="TOPO CENTRO naudų programa" href="<?= $block->escapeUrl($block->getUrl('topoklubas')) ?>"><?= __('TOPO CENTRO naudų programa') ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getUrl('karjera')) ?>"><?= __('Karjera') ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getUrl('verslui')) ?>"><?= __('Verslui') ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getUrl('kontaktai')) ?>"><?= __('Kontaktai') ?></a></li>
            <li><a href="<?= $block->escapeUrl($block->getUrl('ziniasklaidai')) ?>"><?= __('Žiniasklaidai') ?></a></li>
        </ul>
    </div>
</div>
