<?php
/**
 * Social media section
 */
?>
<div class="footer-social-container">
    <div class="footer-menu-toggle">
        <h2 class="footer-menu-title">
            <a href="#"><?= __('Bendraukime') ?></a>
        </h2>
    </div>
    
    <div class="footer-social-content">
        <div class="social-facebook-container">
            <a class="social-facebook" href="https://www.facebook.com/TOPO.centras" target="_blank" rel="noopener noreferrer">
                <span>Facebook</span>
            </a>
            <div class="social-facebook-like">
                TOPO CENTRAS
                <div class="fb-like" 
                     data-href="https://www.facebook.com/TOPO.centras" 
                     data-width="" 
                     data-layout="button_count" 
                     data-action="like" 
                     data-show-faces="true" 
                     data-share="false">
                </div>
            </div>
        </div>
        
        <ul class="social-icon-container">
            <li>
                <a class="social-instagram" href="https://www.instagram.com/topo_centras/" target="_blank" rel="noopener noreferrer">
                    <span>Instagram</span>
                </a>
            </li>
            <li>
                <a class="social-tiktok" href="https://www.tiktok.com/@topo_centras" target="_blank" rel="noopener noreferrer">
                    <span>TikTok</span>
                </a>
            </li>
            <li>
                <a class="social-youtube" href="https://www.youtube.com/channel/UC76neYkdxj0v2hIH0YCY4Xw" target="_blank" rel="noopener noreferrer">
                    <span>Youtube</span>
                </a>
            </li>
            <li>
                <a class="social-linkedin" href="https://lt.linkedin.com/company/topo-grup-" target="_blank" rel="noopener noreferrer">
                    <span>LinkedIn</span>
                </a>
            </li>
        </ul>
    </div>
</div>
