<?php
/**
 * Topo Klubas Banner
 */
?>
<div class="footer-topoklubas-banner">
    <p>
        <a href="<?= $block->escapeUrl($block->getUrl('topoklubas')) ?>" aria-label="Topo klubas">
            <img src="https://picfit.topocentras.lt/xcdn-cgi/image/fit=contain,format=auto,quality=85/media/wysiwyg/ltb/tk_ftr.png" 
                 alt="Topo Klubas" 
                 width="490" 
                 height="150" 
                 style="margin-bottom: 20px;">
        </a>
    </p>
</div>
