<div class="category-menu-wrapper">
    <div class="category-menu">
        <ul class="category-list">
            <li class="category-item" data-desktop_menu_dropdown_item="1090">
                <a class="category-link" href="/telefonai-navigacijos-auto-iranga.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/telefonai_1.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Telefonai, laikrodžiai, Foto'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="1090" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Telefonai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/telefonai-navigacijos-auto-iranga/ismanieji-telefonai.html">
                                <span><?php echo __('Mobilieji telefonai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobilieji-telefonai.html?product_brand=5925"><span><?php echo __('Apple telefonai'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span></a></li>
                            <li><a href="/megaukis-naujomis-galimybemis-su-samsung-galaxy-ai.html"><span><?php echo __('Galaxy AI telefonai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobilieji-telefonai.html?product_brand=5836"><span><?php echo __('Samsung telefonai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobilieji-telefonai.html?product_brand=7370"><span><?php echo __('Xiaomi telefonai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobilieji-telefonai.html?product_brand=35125"><span><?php echo __('Nothing telefonai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/atnaujinti-ismanieji-telefonai.html"><span><?php echo __('Atnaujinti telefonai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobilieji-telefonai.html"><span><?php echo __('Visi telefonai ❯'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/telefonai-navigacijos-auto-iranga/mobiliuju-telefonu-priedai-aksesuarai.html">
                                <span><?php echo __('Mobiliųjų telefonų priedai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobiliuju-telefonu-priedai-aksesuarai/telefonu-deklai.html?ext_param_2710=60843%2C60844"><span><?php echo __('iPhone 17 Pro dėkliukai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobiliuju-telefonu-priedai-aksesuarai/telefonu-deklai.html?ext_param_2710=60588"><span><?php echo __('iPhone 17 dėkliukai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobiliuju-telefonu-priedai-aksesuarai/telefonu-deklai.html"><span><?php echo __('Dėkliukai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobiliuju-telefonu-priedai-aksesuarai/ekrano-pleveles.html"><span><?php echo __('Ekrano stikliukai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobiliuju-telefonu-priedai-aksesuarai/isorines-baterijos.html"><span><?php echo __('Išorinės baterijos'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobiliuju-telefonu-priedai-aksesuarai/tinklo-ikrovikliai.html"><span><?php echo __('Tinklo įkrovikliai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobiliuju-telefonu-priedai-aksesuarai/telefonu-laikikliai.html"><span><?php echo __('Telefonų laikikliai (Auto)'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobiliuju-telefonu-priedai-aksesuarai/laidai.html"><span><?php echo __('Laidai telefonams (įkrovimo)'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Laikrodžiai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/telefonai-navigacijos-auto-iranga/ismanieji-laikrodziai.html">
                                <span><?php echo __('Išmanieji laikrodžiai ir apyrankės'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/telefonai-navigacijos-auto-iranga/ismanieji-laikrodziai.html"><span><?php echo __('Išmanieji laikrodžiai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/ismaniosios-apyrankes.html"><span><?php echo __('Išmaniosios apyrankės'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/ismanieji-laikrodziai.html?ext_param_2785=28439"><span><?php echo __('Laikrodžiai vaikams'); ?></span></a></li>
                            <li><a href="/apple-laikrodziai.html"><span><?php echo __('Apple Watch laikrodžiai'); ?></span></a></li>
                            <li><a href="/galaxy-ismanieji-laikrodziai.html?order=discount&amp;p=1"><span><?php echo __('Samsung laikrodžiai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/ismanieji-laikrodziai.html?product_brand=6438"><span><?php echo __('Garmin laikrodžiai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/ismanieji-laikrodziai.html?product_brand=7370"><span><?php echo __('Xiaomi laikrodžiai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/ismanieji-laikrodziai.html?product_brand=7068"><span><?php echo __('Huawei laikrodžiai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/ismanieji-laikrodziai.html"><span><?php echo __('Visi laikrodžiai ❯'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title">
                            <a href="/telefonai-navigacijos-auto-iranga/ismaniuju-laikrodziu-aksesuarai.html">
                                <span><?php echo __('Laikrodžių aksesuarai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/telefonai-navigacijos-auto-iranga/ismanieji-ziedai.html">
                                <span><?php echo __('Išmanieji žiedai'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Foto, Video įranga'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/fotoaparatai-ir-kameros.html">
                                <span><?php echo __('Fotoaparatai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/fotoaparatai-ir-kameros/skaitmeniniai-fotoaparatai.html"><span><?php echo __('Skaitmeniniai'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/veidrodiniai-fotoaparatai.html"><span><?php echo __('Veidrodiniai (SLR)'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/sisteminiai-fotoaparatai.html"><span><?php echo __('Sisteminiai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/fotoaparatai-ir-kameros/video-kameros.html">
                                <span><?php echo __('Filmavimo kameros'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/fotoaparatai-ir-kameros/video-kameros/gopro-veiksmo-kameros.html"><span><?php echo __('Veiksmo kameros (GoPro ir kt.)'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/video-kameros/vaizdo-kameros.html"><span><?php echo __('Vaizdo kameros'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/registratoriai.html"><span><?php echo __('Vaizdo registratoriai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/fotoaparatai-ir-kameros/kameru-fotoaparatu-priedai.html">
                                <span><?php echo __('Fotoaparatų ir kamerų priedai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/fotoaparatai-ir-kameros/kameru-fotoaparatu-priedai/objektyvai.html"><span><?php echo __('Objektyvai'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/kameru-fotoaparatu-priedai/blykstes.html"><span><?php echo __('Blykstės'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/kameru-fotoaparatu-priedai/filtrai.html"><span><?php echo __('Filtrai'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/kameru-fotoaparatu-priedai/statyvai.html"><span><?php echo __('Štatyvai'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/kameru-fotoaparatu-priedai/deklai-kameroms-fotoaparatams.html"><span><?php echo __('Dėklai kameroms, fotoaparatams'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/kameru-fotoaparatu-priedai/akumuliatoriai-ikrovikliai.html"><span><?php echo __('Akumuliatoriai, įkrovikliai'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Foto, Video priedai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/fotoaparatai-ir-kameros/atminties-korteles.html">
                                <span><?php echo __('Atminties kortelės'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/fotoaparatai-ir-kameros/atminties-korteles/sd.html"><span><?php echo __('SD kortelės'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/atminties-korteles/micro-sd.html"><span><?php echo __('Micro SD'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/atminties-korteles/compact-flash.html"><span><?php echo __('Compact Flash'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/atminties-korteles/korteliu-skaitytuvai.html"><span><?php echo __('Kortelių skaitytuvai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title">
                            <a href="/kiti-priedai-dalys.html">
                                <span><?php echo __('Kiti priedai, dalys'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/fotoaparatai-ir-kameros/kameru-fotoaparatu-priedai/akumuliatoriai-ikrovikliai.html"><span><?php echo __('Akumuliatoriai, įkrovikliai'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/kameru-fotoaparatu-priedai/daugiau-foto-priedu.html"><span><?php echo __('Daugiau foto priedų'); ?></span></a></li>
                            <li><a href="/fotoaparatai-ir-kameros/kameru-fotoaparatu-priedai/daugiau-kameru-priedu.html"><span><?php echo __('Daugiau kamerų priedų'); ?></span></a></li>
                        </ul>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="1091">
                <a class="category-link" href="/kompiuteriai-ir-plansetes.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/Kompiuteriai_1.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Kompiuterinė technika'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="1091" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Kompiuteriai, planšetės'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/nesiojamieji-kompiuteriai.html">
                                <span><?php echo __('Nešiojamieji kompiuteriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/mac.html?in_categories=1379">
                                <span><?php echo __('Apple MacBook'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/stacionarus-kompiuteriai.html">
                                <span><?php echo __('Stacionarūs kompiuteriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai.html">
                                <span><?php echo __('Žaidimų kompiuteriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/plansetes.html">
                                <span><?php echo __('Planšetiniai kompiuteriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/monitoriai.html">
                                <span><?php echo __('Monitoriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimu-monitoriai.html">
                                <span><?php echo __('Žaidimų monitoriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/nesiojamuju-kompiuteriu-priedai-aksesuarai.html">
                                <span><?php echo __('Nešiojamųjų kompiuterių priedai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kompiuteriai-ir-plansetes/nesiojamuju-kompiuteriu-priedai-aksesuarai/ikrovikliai.html"><span><?php echo __('Įkrovikliai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/nesiojamuju-kompiuteriu-priedai-aksesuarai/ausinimo-padai.html"><span><?php echo __('Aušinimo padai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/nesiojamuju-kompiuteriu-priedai-aksesuarai/deklai-kompiuteriams.html"><span><?php echo __('Krepšiai, kuprinės, dėklai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/planseciu-priedai-aksesuarai.html">
                                <span><?php echo __('Planšečių priedai, aksesuarai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kompiuteriai-ir-plansetes/planseciu-priedai-aksesuarai/planseciu-deklai.html"><span><?php echo __('Planšečių dėklai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/planseciu-priedai-aksesuarai/planseciu-ekranu-pleveles.html"><span><?php echo __('Ekrano plėvelės'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Kompiuterių priedai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/peles-klaviaturos-ir-kilimeliai.html">
                                <span><?php echo __('Išoriniai kompiuterių priedai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kompiuteriai-ir-plansetes/peles-klaviaturos-ir-kilimeliai/peles.html"><span><?php echo __('Pelės'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/peles-klaviaturos-ir-kilimeliai/klaviaturos.html"><span><?php echo __('Klaviatūros'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/peles-klaviaturos-ir-kilimeliai/peliu-kilimeliai.html"><span><?php echo __('Kilimėliai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/kameros-ir-ausines-mikrofonai.html">
                                <span><?php echo __('Kameros, ausinės, mikrofonai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kompiuteriai-ir-plansetes/kameros-ir-ausines-mikrofonai/internetines-kameros.html"><span><?php echo __('Internetinės kameros'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/kameros-ir-ausines-mikrofonai/ausines.html"><span><?php echo __('Ausinės (kompiuterinės)'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/kameros-ir-ausines-mikrofonai/mikrofonai.html"><span><?php echo __('Mikrofonai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/koloneles.html">
                                <span><?php echo __('Kompiuterio kolonėlės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/isorines-duomenu-laikmenos.html">
                                <span><?php echo __('Išorinės duomenų laikmenos'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/kompiuteriu-komponentai.html">
                                <span><?php echo __('Kompiuterių komponentai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kompiuteriai-ir-plansetes/kompiuteriu-komponentai/vidiniai-ssd-diskai.html"><span><?php echo __('Vidiniai SSD diskai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/kompiuteriu-komponentai/vaizdo-plokstes.html"><span><?php echo __('Vaizdo plokštės'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/kompiuteriu-komponentai/operatyviosios-atmintys.html"><span><?php echo __('Operatyvioji atmintis (RAM)'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/kompiuteriu-komponentai.html"><span><?php echo __('Kiti komponentai..'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Biuro įranga'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/televizoriai-ir-garso-technika/projektoriai.html">
                                <span><?php echo __('Projektoriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/televizoriai-ir-garso-technika/ekranai.html">
                                <span><?php echo __('Ekranai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/spausdintuvai-ir-ju-priedai.html">
                                <span><?php echo __('Spausdintuvai ir jų priedai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kompiuteriai-ir-plansetes/spausdintuvai-ir-ju-priedai/spausdintuvai.html"><span><?php echo __('Spausdintuvai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/spausdintuvai-ir-ju-priedai/lazerines-kasetes.html"><span><?php echo __('Lazerinės kasetės (toneriai)'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/spausdintuvai-ir-ju-priedai/rasalines-kasetes.html"><span><?php echo __('Rašalinės kasetės (toneriai)'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/spausdintuvai-ir-ju-priedai/rasaliniu-papildai.html"><span><?php echo __('Rašalinių kasečių papildai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/spausdintuvai-ir-ju-priedai/popierius.html"><span><?php echo __('Popierius'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/spausdintuvai-ir-ju-priedai/kitos-eksplotacines-medziagos.html"><span><?php echo __('Kitos eksploatacinės medžiagos'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/skeneriai.html">
                                <span><?php echo __('Skeneriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/programine-iranga.html">
                                <span><?php echo __('Programinė įranga'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kompiuteriai-ir-plansetes/programine-iranga/operacines-sistemos.html"><span><?php echo __('Operacinės sistemos'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/programine-iranga/antivirusines-programos.html"><span><?php echo __('Antivirusinės programos'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/programine-iranga/microsoft-office.html"><span><?php echo __('Microsoft Office'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Kita kompiuterinė technika'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/e-skaitykles.html">
                                <span><?php echo __('E-skaityklės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/piesimo-plansetes.html">
                                <span><?php echo __('Piešimo planšetės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/spausdintuvai-ir-ju-priedai/3d-spausdintuvai.html">
                                <span><?php echo __('3D spausdintuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/nepertraukiamo-maitinimo-saltiniai.html">
                                <span><?php echo __('Nepertraukiamo maitinimo šaltiniai (UPS)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/sroves-lygintuvai.html">
                                <span><?php echo __('Srovės lygintuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/laidai.html">
                                <span><?php echo __('Laidai (IT)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/adapteriai.html">
                                <span><?php echo __('Adapteriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/valymo-priemones.html">
                                <span><?php echo __('Valymo priemonės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/tinklo-iranga.html">
                                <span><?php echo __('Tinklo įranga'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kompiuteriai-ir-plansetes/tinklo-iranga/marsrutizatoriai.html"><span><?php echo __('Maršrutizatoriai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/tinklo-iranga/wifi-tinklo-adapteriai.html"><span><?php echo __('WiFi tinklo adapteriai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/tinklo-iranga/usb-sakotuvai.html"><span><?php echo __('USB šakotuvai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/tinklo-iranga.html"><span><?php echo __('Visos prekės ❯'); ?></span></a></li>
                        </ul>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="4215">
                <a class="category-link" href="/buitine-technika/virtuves-buitine-technika.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/virtuves-technika.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Virtuvės buitinė technika, Kava'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="4215" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Stambi virtuvės technika'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/saldytuvai.html">
                                <span><?php echo __('Šaldytuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/saldikliai.html">
                                <span><?php echo __('Šaldikliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/indaploves.html">
                                <span><?php echo __('Indaplovės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/virtuves-buitine-technika/virykles.html">
                                <span><?php echo __('Viryklės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/mikrobangu-krosneles.html">
                                <span><?php echo __('Mikrobangų krosnelės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/virtuves-buitine-technika/mini-virykl.html">
                                <span><?php echo __('Mini viryklės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/virtuves-buitine-technika/mini-orkaites.html">
                                <span><?php echo __('Mini orkaitės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/namu-apyvokos-prekes/virtuves-iranga/virtuves-baldu-komplektai.html">
                                <span><?php echo __('VOKĖ III virtuvės baldai'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Įmontuojama virtuvės technika'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/imontuojama-buitine-technika/imontuojamos-orkaites.html">
                                <span><?php echo __('Orkaitės (įmontuojamos)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/imontuojama-buitine-technika/imontuojamos-kaitlentes.html">
                                <span><?php echo __('Kaitlentės (įmontuojamos)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/gartraukiai-filtrai.html">
                                <span><?php echo __('Gartraukiai (įmontuojami)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/imontuojama-buitine-technika/imontuojami-saldytuvai.html">
                                <span><?php echo __('Šaldytuvai (įmontuojami)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/imontuojama-buitine-technika/imontuojamos-indaploves.html">
                                <span><?php echo __('Indaplovės (įmontuojamos)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/imontuojama-buitine-technika/imontuojamos-mikrobangu-krosneles.html">
                                <span><?php echo __('Mikrobangų krosnelės (įmontuojamos)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/imontuojama-buitine-technika/imontuojami-kavos-aparatai.html">
                                <span><?php echo __('Kavos aparatai (įmontuojami)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/imontuojama-buitine-technika/imontuojami-saldikliai.html">
                                <span><?php echo __('Šaldikliai (įmontuojami)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/imontuojama-buitine-technika/imontuojami-sildymo-stalciai.html">
                                <span><?php echo __('Šildymo stalčiai (įmontuojami)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/namu-apyvokos-prekes/virtuves-iranga.html">
                                <span><?php echo __('Plautuvės ir vandens maišytuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/imontuojama-buitine-technika.html">
                                <span><?php echo __('Visos prekės ❯'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Kava'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/kava-ir-kavos-aparatai/kavos-aparatai.html">
                                <span><?php echo __('Kavos aparatai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/kava-ir-kavos-aparatai/kava.html">
                                <span><?php echo __('Kava, kavos pupelės ir kapsulės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/kava-ir-kavos-aparatai/pieno-saldytuvai-kavos-aparatu-valymo-priedai.html">
                                <span><?php echo __('Pieno šaldytuvai, kavos aparatų priedai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/kava-ir-kavos-aparatai/kavamales.html">
                                <span><?php echo __('Kavamalės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/kava-ir-kavos-aparatai/pieno-plakikliai.html">
                                <span><?php echo __('Pieno plakikliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/kava-ir-kavos-aparatai/kavinukai.html">
                                <span><?php echo __('Kavinukai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/kava-ir-kavos-aparatai.html">
                                <span><?php echo __('Visos prekės ❯'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/jura">
                                <span><?php echo __('JURA parduotuvė'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/delonghi">
                                <span><?php echo __('De\'Longhi parduotuvė'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/nespresso">
                                <span><?php echo __('NESPRESSO parduotuvė'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Maisto ruošimui'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/gruzdintuves-fritiurines.html?ext_param_3256=38608">
                                <span><?php echo __('Karšto oro gruzdintuvės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/virduliai.html">
                                <span><?php echo __('Virduliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/virtuviniai-kombainai.html">
                                <span><?php echo __('Virtuviniai kombainai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/gruzdintuves-fritiurines.html">
                                <span><?php echo __('Gruzdintuvės (Fritiūrinės)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/blenderiai.html">
                                <span><?php echo __('Blenderiai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/kokteilines.html">
                                <span><?php echo __('Kokteilinės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/leduku-gamybos-aparatai.html">
                                <span><?php echo __('Ledukų gaminimo aparatai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/gerimu-gaminimo-aparatai.html">
                                <span><?php echo __('Gėrimų ir vaisvandenių gamyba (SodaStream)'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/sumustiniu-keptuves.html">
                                <span><?php echo __('Sumuštinių keptuvės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/virtuves-buitine-technika/mini-griliai.html">
                                <span><?php echo __('Mini griliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/vaflines-blynines-spurgines.html">
                                <span><?php echo __('Vaflinės, blyninės, spurginės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/sulciaspaudes.html">
                                <span><?php echo __('Sulčiaspaudės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/skrudintuvai-tosteriai.html">
                                <span><?php echo __('Skrudintuvai (tosteriai)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/mesmales.html">
                                <span><?php echo __('Mėsmalės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/vakuumavimo-aparatai.html">
                                <span><?php echo __('Vakuumavimo aparatai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/tarkavimo-masinos.html">
                                <span><?php echo __('Tarkavimo mašinos'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/maisto-ruosimo-puodai.html">
                                <span><?php echo __('Puodai, keptuvės, indai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai.html">
                                <span><?php echo __('Visos prekės ❯'); ?></span>
                            </a>
                        </h5>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="1088">
                <a class="category-link" href="/buitine-technika.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/buitine-technika_1.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Buitinė technika namams'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="1088" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Namų valymo technika'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/dulkiu-siurbliai-priedai/dulkiu-siurbliai-robotai.html">
                                <span><?php echo __('Dulkių siurbliai - robotai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/dulkiu-siurbliai-priedai/dulkiu-siurbliai-sluotos.html">
                                <span><?php echo __('Dulkių siurbliai - šluotos'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/dulkiu-siurbliai-priedai/dulkiu-siurbliai.html">
                                <span><?php echo __('Dulkių siurbliai - klasikiniai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/dulkiu-siurbliai-priedai/dulkiu-siurbliu-priedai.html">
                                <span><?php echo __('Dulkių siurblių priedai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/dulkiu-siurbliai-priedai.html">
                                <span><?php echo __('Visi siurbliai ❯'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/dulkiu-siurbliai-priedai/dulkiu-siurbliai-sluotos/dyson.html">
                                <span><?php echo __('Dyson dulkių sirbliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/langu-valymo-prietaisai.html">
                                <span><?php echo __('Langų valymo prietaisai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/namu-apyvokos-prekes.html">
                                <span><?php echo __('Namų apyvokos prekės'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Skalbyklės ir džiovyklės'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/skalbykles.html">
                                <span><?php echo __('Skalbimo mašinos'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/skalbykles.html?ext_param_2213=8475">
                                <span><?php echo __('Skalbyklės - džiovyklės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/dziovykles.html">
                                <span><?php echo __('Džiovyklės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/namu-apyvokos-prekes/chemijos-priemones/skalbimo-priemones.html">
                                <span><?php echo __('Skalbimo priemonės'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Klimato kontrolės technika'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/klimato-kontroles-technika/sildytuvai.html">
                                <span><?php echo __('Šildytuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/klimato-kontroles-technika/radiatoriai.html">
                                <span><?php echo __('Radiatoriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/klimato-kontroles-technika/drekintuvai.html">
                                <span><?php echo __('Oro drėkintuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/klimato-kontroles-technika/ventiliatoriai.html">
                                <span><?php echo __('Ventiliatoriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/klimato-kontroles-technika/kondicionieriai.html">
                                <span><?php echo __('Oro kondicionieriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/klimato-kontroles-technika/sausintuvai.html">
                                <span><?php echo __('Oro sausintuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/klimato-kontroles-technika/oro-valytuvai.html">
                                <span><?php echo __('Oro valytuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/klimato-kontroles-technika/infraraudonuju-spinduliu-sildytuvai.html">
                                <span><?php echo __('Infraraudonųjų spindulių šildytuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/klimato-kontroles-technika/meteorologines-stoteles.html">
                                <span><?php echo __('Meteorologinės stotelės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/klimato-kontroles-technika/aromato-skleidikliai.html">
                                <span><?php echo __('Aromato skleidikliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/klimato-kontroles-technika.html">
                                <span><?php echo __('Visos prekės ❯'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/klimato-kontroles-technika/oro-valytuvai/dyson-oro-valytuvai.html">
                                <span><?php echo __('Dyson oro priežiūros technika'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Drabužių priežiūros technika'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/rubu-avalynes-prieziuros-prietaisai/lygintuvai.html">
                                <span><?php echo __('Lygintuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/rubu-avalynes-prieziuros-prietaisai/drabuziu-garintuvai.html">
                                <span><?php echo __('Drabužių garintuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/rubu-avalynes-prieziuros-prietaisai/lyginimo-sistemos.html">
                                <span><?php echo __('Lyginimo sistemos'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/rubu-avalynes-prieziuros-prietaisai/siuvimo-masinos.html">
                                <span><?php echo __('Siuvimo mašinos'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/rubu-avalynes-prieziuros-prietaisai/puku-surinktuvai.html">
                                <span><?php echo __('Pūkų surinktuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/drabuziu-prieziuros-sistemos.html">
                                <span><?php echo __('Drabužių priežiūros sistemos'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/rubu-avalynes-prieziuros-prietaisai/batu-dziovintuvai.html">
                                <span><?php echo __('Batų džiovintuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/rubu-avalynes-prieziuros-prietaisai.html">
                                <span><?php echo __('Visos prekės ❯'); ?></span>
                            </a>
                        </h5>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="5692">
                <a class="category-link" href="/vaizdo-technika.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/Televizoriai_ir_garso_technika_1.webp'); ?>');"></i>
                    <span class="category-name"><?php echo __('Televizoriai ir vaizdo technika'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="5692" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Vaizdo technika'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/vaizdo-technika/televizoriai.html">
                                <span><?php echo __('Televizoriai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/vaizdo-technika/televizoriai/samsung.html"><span><?php echo __('Samsung televizoriai'); ?></span></a></li>
                            <li><a href="/vaizdo-technika/televizoriai/lg.html"><span><?php echo __('LG televizoriai'); ?></span></a></li>
                            <li><a href="/vaizdo-technika/televizoriai.html?product_brand=5835"><span><?php echo __('Philips televizoriai'); ?></span></a></li>
                            <li><a href="/vaizdo-technika/televizoriai.html?product_brand=7370"><span><?php echo __('Xiaomi televizoriai'); ?></span></a></li>
                            <li><a href="/vaizdo-technika/televizoriai.html?product_brand=7141"><span><?php echo __('Hisense televizoriai'); ?></span></a></li>
                            <li><a href="/vaizdo-technika/televizoriai.html?product_brand=42523"><span><?php echo __('Kivi televizoriai'); ?></span></a></li>
                            <li><a href="/vaizdo-technika/televizoriai.html?product_brand=6767"><span><?php echo __('TCL Televizoriai'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span></a></li>
                            <li><a href="/vaizdo-technika/televizoriai/oled-televizoriai.html"><span><?php echo __('OLED televizoriai'); ?></span></a></li>
                            <li><a href="/vaizdo-technika/televizoriai/qled-televizoriai.html"><span><?php echo __('QLED televizoriai'); ?></span></a></li>
                            <li><a href="/vaizdo-technika/televizoriai/qned-televizoriai.html"><span><?php echo __('QNED televizoriai'); ?></span></a></li>
                            <li><a href="/vaizdo-technika/televizoriai/android-google-tv-televizoriai.html"><span><?php echo __('Google TV televizoriai'); ?></span></a></li>
                            <li><a href="/vaizdo-technika/televizoriai.html"><span><?php echo __('Visos prekės ❯'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Išsirinkite TV'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1174=43555%2C43529%2C35307%2C423%2C43532">
                                <span><?php echo __('32" įstrižainė ir mažiau'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1174=43536">
                                <span><?php echo __('42" įstrižainė'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1174=43564">
                                <span><?php echo __('43" įstrižainė'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1174=43590">
                                <span><?php echo __('48" įstrižainė'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1174=43538">
                                <span><?php echo __('50" įstrižainė'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1174=43540">
                                <span><?php echo __('55" įstrižainė'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1174=43560">
                                <span><?php echo __('65" įstrižainė'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1174=43579">
                                <span><?php echo __('75" įstrižainė'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1174=19598">
                                <span><?php echo __('77" įstrižainė'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1174=43630">
                                <span><?php echo __('83" įstrižainė'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1174=43556%2C43596%2C43603">
                                <span><?php echo __('85" įstrižainė ir daugiau'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1524=1169">
                                <span><?php echo __('4K televizoriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1524=35476">
                                <span><?php echo __('8K televizoriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai.html?ext_param_1524=1034">
                                <span><?php echo __('Full HD televizoriai'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('TV priedai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/tv-priedai/tv-laikikliai.html">
                                <span><?php echo __('Televizorių laikikliai ir stovai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/tv-priedai/tv-staliukai.html">
                                <span><?php echo __('Televizorių staliukai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/multi-media-grotuvai.html">
                                <span><?php echo __('Media grotuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/tv-priedai/nuotolinio-valdymo-pultai.html">
                                <span><?php echo __('Nuotolinio valdymo pultai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/tv-priedai/tv-antenos.html">
                                <span><?php echo __('Televizorių antenos'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/tv-priedai.html">
                                <span><?php echo __('Visi priedai ❯'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/garso-technika/garso-sistemos.html">
                                <span><?php echo __('Soundbar garso sistemos'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Kita vaizdo technika'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/multi-media-grotuvai.html">
                                <span><?php echo __('Multi-media grotuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/projektoriai.html">
                                <span><?php echo __('Projektoriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/ekranai.html">
                                <span><?php echo __('Ekranai projektoriams'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/projektoriu-priedai.html">
                                <span><?php echo __('Projektorių priedai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/vaizdo-technika/televizoriai/komerciniai-ekranai-digital-signage.html">
                                <span><?php echo __('Komerciniai ekranai'); ?></span>
                            </a>
                        </h5>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="1089">
                <a class="category-link" href="/garso-technika.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/garso_technika.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Garso technika'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="1089" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Ausinės'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/garso-technika/ausines/belaides-ausines.html">
                                <span><?php echo __('Belaidės ausinės (True wireless)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/apple-airpods.html">
                                <span><?php echo __('Apple AirPods'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/ausines/belaides-ausines-dedamos-ant-ausu.html">
                                <span><?php echo __('Belaidės ausinės dedamos ant ausų'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/ausines/ausines-laidines.html">
                                <span><?php echo __('Ausinės laidinės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/zaidimu-ausines.html">
                                <span><?php echo __('Žaidimų ausinės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/ausines.html">
                                <span><?php echo __('Visos ausinės ❯'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/ausines/ausiniu-priedai.html">
                                <span><?php echo __('Ausinių priedai'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Kolonėlės'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/garso-technika/koloneles/nesiojamosios-koloneles.html">
                                <span><?php echo __('Nešiojamos kolonėlės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/koloneles/vakareliu-koloneles.html">
                                <span><?php echo __('Vakarėlių kolonėlės'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/koloneles/belaides-wifi-garso-koloneles.html">
                                <span><?php echo __('Belaidės WiFi kolonėlės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/ismaniosios-koloneles.html">
                                <span><?php echo __('Išmaniosios kolonėlės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/garso-koloneles.html">
                                <span><?php echo __('Garso kolonėlės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/koloneles.html">
                                <span><?php echo __('Visos kolonėlės ❯'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/garso-technika/garso-sistemos.html">
                                <span><?php echo __('Garso sistemos (Soundbar)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/garso-technika/namu-kino-sistemos.html">
                                <span><?php echo __('Namų kino sistemos'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Garso technika'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/garso-technika/muzikiniai-centrai.html">
                                <span><?php echo __('Muzikiniai centrai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/ploksteliu-grotuvai.html">
                                <span><?php echo __('Plokštelių grotuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/magnetolos-ir-radijo-grotuvai.html">
                                <span><?php echo __('Magnetolos'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/dvd-blu-ray-grotuvai.html">
                                <span><?php echo __('DVD ir Blu-ray grotuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/mp3-grotuvai.html">
                                <span><?php echo __('Mp3 grotuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/radijos.html">
                                <span><?php echo __('Radijos'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/radijo-zadintuvai.html">
                                <span><?php echo __('Radijo žadintuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/garso-technika/vinilines-ploksteles.html">
                                <span><?php echo __('Vinilinės plokštelės'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Kita garso technika'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/garso-technika/garso-stiprintuvai.html">
                                <span><?php echo __('Garso stiprintuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/mikrofonai.html">
                                <span><?php echo __('Mikrofonai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/muzikos-instrumentai-ir-priedai.html">
                                <span><?php echo __('Muzikos instrumentai ir priedai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/diktofonai.html">
                                <span><?php echo __('Diktofonai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/garso-technika/aparaturos-sujungimas-laidai-ir-kabeliai.html">
                                <span><?php echo __('Aparatūros sujungimas'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/garso-technika/aparaturos-sujungimas-laidai-ir-kabeliai/jungiamieji-laidai.html"><span><?php echo __('Jungiamieji laidai'); ?></span></a></li>
                            <li><a href="/garso-technika/aparaturos-sujungimas-laidai-ir-kabeliai/prailgintuvai.html"><span><?php echo __('Prailgintuvai'); ?></span></a></li>
                        </ul>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="2452">
                <a class="category-link" href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/TC-ikonos-outlined_Zaidimu-erdve.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Žaidimų erdvė. PS5, XBOX'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="2452" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Įranga žaidėjams'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai.html">
                                <span><?php echo __('Žaidimų kompiuteriai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/playstation-5-zaidimu-konsoles.html"><span><?php echo __('Playstation 5 žaidimų konsolės'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/xbox-zaidimu-konsoles.html"><span><?php echo __('Xbox žaidimų konsolės'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/nintendo-zaidimu-konsoles.html"><span><?php echo __('Nintendo žaidimų konsolės'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/nesiojami-zaidimu-kompiuteriai.html"><span><?php echo __('Nešiojami žaidimų kompiuteriai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/stacionarus-zaidimu-kompiuteriai.html"><span><?php echo __('Stacionarūs žaidimų kompiuteriai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimu-monitoriai.html"><span><?php echo __('Žaidimų monitoriai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/gaming">
                                <span><?php echo __('GAMING ERDVĖ'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Žaidimai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimai.html">
                                <span><?php echo __('Kompiuteriniai žaidimai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimai/ps5-zaidimai.html"><span><?php echo __('Playstation 5 žaidimai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimai/ps4.html"><span><?php echo __('Playstation 4 žaidimai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimai/xbox-series-x-s-zaidimai.html"><span><?php echo __('XBOX Series X/S žaidimai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimai/xbox-one.html"><span><?php echo __('Xbox One žaidimai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimai/nintendo-switch-zaidimai.html"><span><?php echo __('Nintendo Switch žaidimai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimai/pc.html"><span><?php echo __('PC žaidimai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimai/papildymu-kodai-ir-korteles.html">
                                <span><?php echo __('Papildymų kodai ir kortelės'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Lenktynių simuliatorių įranga'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/zaidimu-simuliatoriu-iranga.html">
                                <span><?php echo __('Žaidimų simuliatorių įranga'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/zaidimu-simuliatoriu-iranga.html">
                                <span><?php echo __('Žaidimų simuliatorių kėdės'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/zaidimu-vairai.html">
                                <span><?php echo __('Žaidimų vairai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/zaidimu-vairalazdес.html">
                                <span><?php echo __('Žaidimų vairalazdės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimu-monitoriai.html">
                                <span><?php echo __('Monitoriai'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Priedai žaidėjams'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai.html">
                                <span><?php echo __('Žaidimų kompiuterių priedai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kompiuteriai-ir-plansetes/virtualios-realybes-akiniai.html"><span><?php echo __('VR akiniai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/zaidimu-ausines.html"><span><?php echo __('Žaidimų ausinės'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/zaidimu-klaviaturos.html"><span><?php echo __('Žaidimų klaviatūros'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/zaidimu-peles.html"><span><?php echo __('Žaidimų pelės'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/zaidimu-kedes.html"><span><?php echo __('Žaidimų kėdės'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/peles-kilimeliai-zaidejams.html"><span><?php echo __('Pelės kilimėliai žaidėjams'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/pulteliai.html"><span><?php echo __('Pulteliai'); ?></span></a></li>
                            <li><a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/konsoliu-priedai/kiti-priedai.html"><span><?php echo __('Kiti priedai ❯'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kompiuteriai-ir-plansetes/zaidimu-konsoles-priedai/zaidimu-atributika.html">
                                <span><?php echo __('Žaidimų atributika'); ?></span>
                            </a>
                        </h5>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="2446">
                <a class="category-link" href="/laisvalaikis.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/TC-ikonos-outlined_Laisvalaikis-ir-sportas.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Laisvalaikis, griliai, paspirtukai'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="2446" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Transporto priemonės'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/laisvalaikis/paspirtukai-ir-priedai.html">
                                <span><?php echo __('Elektriniai paspirtukai ir priedai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/elektriniai-motoroleriai.html">
                                <span><?php echo __('Elektriniai motoroleriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/paspirtuku-priedai.html">
                                <span><?php echo __('Paspirtukų priedai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/laisvalaikis/dviraciai-aksesuarai.html">
                                <span><?php echo __('Dviračiai ir aksesuarai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/laisvalaikis/dviraciai-aksesuarai/elektriniai-dviraciai.html"><span><?php echo __('Elektriniai dviračiai'); ?></span></a></li>
                            <li><a href="/laisvalaikis/dviraciai-aksesuarai/dviraciai.html"><span><?php echo __('Dviračiai'); ?></span></a></li>
                            <li><a href="/laisvalaikis/dviraciai-aksesuarai/vaikiski-dviraciai.html"><span><?php echo __('Vaikiški dviračiai'); ?></span></a></li>
                            <li><a href="/laisvalaikis/dviraciai-aksesuarai/dviraciu-aksesuarai-salmai.html"><span><?php echo __('Dviračių aksesuarai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/laisvalaikis/neigaliuju-judejimo-priemones.html">
                                <span><?php echo __('Neįgaliųjų judėjimo priemonės'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/laisvalaikis/neigaliuju-judejimo-priemones/elektriniai-skuteriai.html"><span><?php echo __('Elektriniai skuteriai'); ?></span></a></li>
                            <li><a href="/laisvalaikis/neigaliuju-judejimo-priemones/elektriniai-vezimeliai.html"><span><?php echo __('Elektriniai vežimėliai'); ?></span></a></li>
                            <li><a href="/laisvalaikis/neigaliuju-judejimo-priemones/elektriniu-vezimeliu-ir-skuteriu-priedai.html"><span><?php echo __('Vežimėlių ir skuterių priedai'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Kepsninės'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/laisvalaikis/lauko-kepsnines-ir-priedai.html">
                                <span><?php echo __('Lauko kepsninės ir priedai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/laisvalaikis/lauko-kepsnines-ir-priedai/kamado-kepsnines.html"><span><?php echo __('Kamado kepsninės'); ?></span></a></li>
                            <li><a href="/laisvalaikis/lauko-kepsnines-ir-priedai/anglines-kepsnines.html"><span><?php echo __('Anglinės kepsninės'); ?></span></a></li>
                            <li><a href="/laisvalaikis/lauko-kepsnines-ir-priedai/dujines-kepsnines.html"><span><?php echo __('Dujinės kepsninės'); ?></span></a></li>
                            <li><a href="/laisvalaikis/lauko-kepsnines-ir-priedai/elektrines-kepsnines.html"><span><?php echo __('Elektrinės kepsninės'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/laisvalaikis/lauko-kepsnines-ir-priedai/lauko-kepsniniu-priedai.html">
                                <span><?php echo __('Lauko kepsninių priedai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/laisvalaikis/lauko-kepsnines-ir-priedai/lauko-kepsniniu-priedai/medzo-anglys-ir-briketai.html"><span><?php echo __('Medžio anglys ir briketai'); ?></span></a></li>
                            <li><a href="/laisvalaikis/lauko-kepsnines-ir-priedai/lauko-kepsniniu-priedai/priemones-ugnies-ikurimui.html"><span><?php echo __('Priemonės ugnies įkūrimui'); ?></span></a></li>
                            <li><a href="/laisvalaikis/lauko-kepsnines-ir-priedai/lauko-kepsniniu-priedai/groteles-iesmai-ir-akmenys.html"><span><?php echo __('Grotelės, iešmai ir akmenys'); ?></span></a></li>
                            <li><a href="/laisvalaikis/lauko-kepsnines-ir-priedai/lauko-kepsniniu-priedai/irankiai-kepsninems.html"><span><?php echo __('Įrankiai kepsninėms'); ?></span></a></li>
                            <li><a href="/laisvalaikis/lauko-kepsnines-ir-priedai/lauko-kepsniniu-priedai/keptuves-ir-puodai-griliams.html"><span><?php echo __('Keptuvės ir puodai griliams'); ?></span></a></li>
                            <li><a href="/laisvalaikis/lauko-kepsnines-ir-priedai/lauko-kepsniniu-priedai/termometrai-griliams.html"><span><?php echo __('Termometrai griliams'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Gamtai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/laisvalaikis/stovyklavimo-ir-turizmo-reikmenys/apsauga-nuo-vabzdziu/thermacell.html">
                                <span><?php echo __('Thermacell priemonės nuo uodų'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/stovyklavimo-ir-turizmo-reikmenys/apsauga-nuo-vabzdziu.html">
                                <span><?php echo __('Apsauga nuo vabzdžių'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/buitine-technika/automobilinis-saldytuvas.html">
                                <span><?php echo __('Šaltkrepšiai, nešiojami šaldytuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/stovyklavimo-ir-turizmo-reikmenys.html">
                                <span><?php echo __('Stovyklavimo reikmenys'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Laisvalaikis'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/laisvalaikis/dronai-ir-ju-priedai.html">
                                <span><?php echo __('Dronai'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/laisvalaikis/kitos-laisvalaikio-prekes.html">
                                <span><?php echo __('Visos laisvalaikio prekės ❯'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/zvejybos-reikmenys.html">
                                <span><?php echo __('Žvejybos reikmenys'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/echolotai-deeper-fishfinder-ir-garmin.html">
                                <span><?php echo __('Echolotai Deeper'); ?></span>
                            </a>
                        </h5>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="4389">
                <a class="category-link" href="/sportas-ir-sveikatingumas">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/sportas-ir-sveikatingumas.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Sportas ir sveikatingumas'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="4389" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Treniruočių inventorius'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/treniruokliai.html">
                                <span><?php echo __('Treniruokliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/jega-ir-istverme.html">
                                <span><?php echo __('Jėgai ir ištvermei'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/balansas-ir-koordinacija.html">
                                <span><?php echo __('Balansui ir koordinacijai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/joga-ir-pilatesas.html">
                                <span><?php echo __('Jogai ir pilatesui'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/siaurietisko-ejimo-lazdos.html">
                                <span><?php echo __('Šiaurietiško ėjimo lazdos'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Sporto šakos'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/sporto-sakos/badmintonas.html">
                                <span><?php echo __('Badmintonas'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/sporto-sakos/lauko-tenisas.html">
                                <span><?php echo __('Lauko tenisas'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="//laisvalaikis/sporto-prekes/sporto-sakos/papludimio-tenisas.html">
                                <span><?php echo __('Paplūdimio tenisas'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/sporto-sakos/stalo-tenisas.html">
                                <span><?php echo __('Stalo tenisas'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/sporto-sakos/skvosas.html">
                                <span><?php echo __('Skvošas'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/sporto-sakos/padelis.html">
                                <span><?php echo __('Padelis'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/sporto-sakos/krepsinis.html">
                                <span><?php echo __('Krepšinis'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/sporto-sakos/futbolas.html">
                                <span><?php echo __('Futbolas'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/sporto-sakos/tinklinis.html">
                                <span><?php echo __('Tinklinis'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/sporto-sakos/siaurietiskas-ejimas.html">
                                <span><?php echo __('Šiaurietiškas ėjimas'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/vandens-sportas-ir-plaukimas.html">
                                <span><?php echo __('Vandens sportas'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Aksesuarai ir priedai sportui'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/fizinio-aktyvumo-stebejimo-prietaisai/sportiniai-laikrodziai-ir-apyrankes.html">
                                <span><?php echo __('Sportiniai laikrodžiai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/aksesuarai-ir-priedai-sportui/belaides-ausines-sportui.html">
                                <span><?php echo __('Belaidės ausinės sportui'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/aksesuarai-ir-priedai-sportui/treniruociu-pirstines.html">
                                <span><?php echo __('Treniruočių pirštinės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/reabilitacijai-ir-masazui/masazuokliai.html">
                                <span><?php echo __('Sportiniai masažuokliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/reabilitacijai-ir-masazui/masaziniai-volai.html">
                                <span><?php echo __('Masažiniai volai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/fizinio-aktyvumo-stebejimo-prietaisai/sirdies-ritmo-dirzai.html">
                                <span><?php echo __('Širdies ritmo matavimo diržai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/ismanieji-namai/inovatyvus-prietaisai/ismaniosios-svarstykles.html">
                                <span><?php echo __('Išmaniosios svarstyklės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/reabilitacijai-ir-masazui/itvarai.html">
                                <span><?php echo __('Įtvarai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/aksesuarai-ir-priedai-sportui/kineziologiniai-ir-sporto-pleistrai.html">
                                <span><?php echo __('Kineziologiniai ir sporto pleistrai (Teipai)'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/aksesuarai-ir-priedai-sportui/juosmens-detuves-begimui.html">
                                <span><?php echo __('Juosmens dėtuvės bėgimui'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/laisvalaikis/sporto-prekes/aksesuarai-ir-priedai-sportui/begimo-kuprines.html">
                                <span><?php echo __('Bėgimo kuprinės'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Sveikatingumui'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/vitaminai-ir-maisto-papildai.html">
                                <span><?php echo __('Vitaminai ir maisto papildai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/kokteilines.html">
                                <span><?php echo __('Kokteilinės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/maisto-ruosimo-prietaisai/sulciaspaudes.html">
                                <span><?php echo __('Sulčiaspaudės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/miego-gerinimo-ir-sekimo-prietaisai.html">
                                <span><?php echo __('Miego gerinimo ir sekimo prietaisai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/kraujospudzio-matuokliai.html">
                                <span><?php echo __('Kraujospūdžio matuokliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/gliukozes-matuokliai.html">
                                <span><?php echo __('Gliukozės matuokliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/pulsometrai.html">
                                <span><?php echo __('Pulsometrai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/masazines-voneles.html">
                                <span><?php echo __('Masažinės vonelės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/masazuokliai.html">
                                <span><?php echo __('Masažuokliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/kuno-sildytuvai.html">
                                <span><?php echo __('Kūno šildytuvai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/prietaisai-sviesos-terapijai.html">
                                <span><?php echo __('Prietaisai šviesos terapijai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/antistresinis-prietaisas-beurer-st100.html">
                                <span><?php echo __('Antistresinis prietaisas'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/buitine-technika/klimato-kontroles-technika/aromato-skleidikliai.html">
                                <span><?php echo __('Aromato skleidikliai'); ?></span>
                            </a>
                        </h5>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="2439">
                <a class="category-link" href="/sveikata-grozis-sportas.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/sveikata-ir-grozis_1.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Sveikata, grožis ir higiena'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="2439" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Prietaisai asmens higienai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/sveikata-grozis-sportas/asmenines-higienos-priemones/dantu-sepeteliai.html">
                                <span><?php echo __('Elektriniai dantų šepetėliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/asmenines-higienos-priemones/dantu-sepeteliu-antgaliai.html">
                                <span><?php echo __('Dantų šepetėlių antgaliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/asmenines-higienos-priemones/tarpdanciu-plovikliai.html">
                                <span><?php echo __('Tarpdančių plovikliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/sveikata-grozis-sportas/asmenines-higienos-priemones.html">
                                <span><?php echo __('Higienos priemonės moterims'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/sveikata-grozis-sportas/asmenines-higienos-priemones/epiliatoriai.html"><span><?php echo __('Epiliatoriai'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/asmenines-higienos-priemones/fotoepiliatoriai.html"><span><?php echo __('Fotoepiliatoriai'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/asmenines-higienos-priemones/skustuvai-moterims.html"><span><?php echo __('Skustuvai moterims'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/sveikata-grozis-sportas/asmenines-higienos-priemones.html">
                                <span><?php echo __('Higienos priemonės vyrams'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/sveikata-grozis-sportas/asmenines-higienos-priemones/barzdaskutes.html"><span><?php echo __('Barzdaskutės'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/asmenines-higienos-priemones/trimeriai.html"><span><?php echo __('Trimeriai barzdai'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/asmenines-higienos-priemones/nosies-plauku-kirpimo-masinele.html"><span><?php echo __('Nosies plaukų kirpimo mašinėlės'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/asmenines-higienos-priemones/barzdaskuciu-priedai.html"><span><?php echo __('Barzdaskučių priedai'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Prietaisai grožiui ir sveikatai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/sveikata-grozis-sportas/plauku-prieziura.html">
                                <span><?php echo __('Plaukų priežiūra'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/sveikata-grozis-sportas/plauku-prieziura/plauku-dziovintuvai.html"><span><?php echo __('Plaukų džiovintuvai'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/plauku-prieziura/plauku-tiesinimas.html"><span><?php echo __('Plaukų tiesintuvai'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/plauku-prieziura/znyples.html"><span><?php echo __('Plaukų žnyplės'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/plauku-prieziura/plauku-formavimo-sukos.html"><span><?php echo __('Plaukų formavimo šukos'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/plauku-prieziura/suktukai.html"><span><?php echo __('Plaukų suktukai'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/plauku-prieziura/plauku-kirpimo-masinele.html"><span><?php echo __('Plaukų kirpimo mašinėlės'); ?></span></a></li>
                            <li><a href="/dyson.html"><span><?php echo __('Dyson prietaisai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/veidrodziai.html">
                                <span><?php echo __('Veidrodžiai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/grozio-prietaisai.html">
                                <span><?php echo __('Grožio prietaisai'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/svarstykles.html">
                                <span><?php echo __('Vonios svarstyklės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/masazuokliai.html">
                                <span><?php echo __('Masažuokliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/masazines-voneles.html">
                                <span><?php echo __('Kojų masažinės vonelės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/kraujospudzio-matuokliai.html">
                                <span><?php echo __('Kraujospūdžio matuokliai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/sveikata-grozis-sportas/kitos-sveikatos-prekes.html">
                                <span><?php echo __('Šildančios antklodės ir pagalvės'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Sveikatos apsauga'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/sveikata-grozis-sportas/sveikatos-apsaugos-priemones.html">
                                <span><?php echo __('Sveikatos apsaugos priemonės'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/sveikata-grozis-sportas/sveikatos-apsaugos-priemones/respiratoriai-ir-medicinines-kaukes.html"><span><?php echo __('Respiratoriai ir apsaugos priemonės'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/sveikatos-apsaugos-priemones/dezinfekciniai-skysciai.html"><span><?php echo __('Dezinfekciniai skysčiai'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Grožiui'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/kosmetika.html">
                                <span><?php echo __('Kosmetika'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/kosmetika/veido-prieziuros-priemones.html"><span><?php echo __('Veido priežiūros priemonės'); ?></span></a></li>
                            <li><a href="/kosmetika/kuno-prieziuros-priemones.html"><span><?php echo __('Kūno priežiūros priemonės'); ?></span></a></li>
                            <li><a href="/kosmetika/plauku-prieziuros-priemones.html"><span><?php echo __('Plaukų priežiūros priemonės'); ?></span></a></li>
                        </ul>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="2448">
                <a class="category-link" href="/darbo-irankiai.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/TC-ikonos-outlined_Darbo-irankiai.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Vejos robotai. Darbui ir sodui.'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="2448" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Sodui'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/darbo-irankiai/sodo-technika.html">
                                <span><?php echo __('Sodo technika'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/darbo-irankiai/sodo-technika/vejos-robotai.html"><span><?php echo __('Vejos pjovimo robotai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/sodo-technika/zoliapjoves.html"><span><?php echo __('Žoliapjovės'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/sodo-technika/lapu-pustuvai.html"><span><?php echo __('Lapų pūstuvai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/sodo-technika/vandens-siurbliai.html"><span><?php echo __('Vandens siurbliai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title">
                            <a href="/darbo-irankiai/sodo-technika/sodo-ir-darzo-irankiai.html">
                                <span><?php echo __('Sodo ir daržo įrankiai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/darbo-irankiai/sodo-technika/sodo-ir-darzo-irankiai/kastuvai.html"><span><?php echo __('Kastuvai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/sodo-technika/sodo-ir-darzo-irankiai/kirviai.html"><span><?php echo __('Kirviai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/sodo-technika/sodo-ir-darzo-irankiai/laistymo-zarnos.html"><span><?php echo __('Laistymo žarnos'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/sodo-technika/sodo-ir-darzo-irankiai/sodo-zirkles.html"><span><?php echo __('Sodo žirklės'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/sodo-technika/sodo-ir-darzo-irankiai/kiti-sodo-irankai.html"><span><?php echo __('Kiti sodo įrankai'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Laidiniai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/darbo-irankiai/elektriniai-darbo-irankiai/laidiniai-irankiai.html">
                                <span><?php echo __('Laidiniai darbo įrankiai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/laidiniai-irankiai/grezimo-irankiai.html"><span><?php echo __('Gręžimo įrankiai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/laidiniai-irankiai/perforatoriai.html"><span><?php echo __('Perforatoriai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/laidiniai-irankiai/pjovimo-irankiai.html"><span><?php echo __('Pjovimo įrankiai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/laidiniai-irankiai/slifuokliai.html"><span><?php echo __('Šlifuokliai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/laidiniai-irankiai/daugiafunkciniai-irankiai.html"><span><?php echo __('Daugiafunkciniai įrankiai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/laidiniai-irankiai/obliavimo-irankiai.html"><span><?php echo __('Obliavimo įrankiai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/laidiniai-irankiai/dazymo-irankiai.html"><span><?php echo __('Dažymo įrankiai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/laidiniai-irankiai/kiti-elektriniai-irankiai.html"><span><?php echo __('Kiti elektriniai įrankiai'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Akumuliatoriniai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/darbo-irankiai/elektriniai-darbo-irankiai/akumuliatoriniai-irankiai.html">
                                <span><?php echo __('Akumuliatoriniai darbo įrankiai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/akumuliatoriniai-irankiai/suktuvai-ir-greztuvai.html"><span><?php echo __('Suktuvai ir gręžtuvai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/akumuliatoriniai-irankiai/pjovimo-irankiai.html"><span><?php echo __('Pjovimo įrankiai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/akumuliatoriniai-irankiai/perforatoriai.html"><span><?php echo __('Perforatoriai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/akumuliatoriniai-irankiai/diskiniai-pjuklai.html"><span><?php echo __('Diskiniai pjūklai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/akumuliatoriniai-irankiai/slifuokliai.html"><span><?php echo __('Šlifuokliai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/akumuliatoriniai-irankiai/daugiafunkciniai-irankiai.html"><span><?php echo __('Daugiafunkciniai įrankiai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/akumuliatoriniai-irankiai/gyvatvoriu-zirkles.html"><span><?php echo __('Gyvatvorių žirklės'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/akumuliatoriniai-irankiai/matavimo-prietaisai.html"><span><?php echo __('Matavimo prietaisai'); ?></span></a></li>
                            <li><a href="/darbo-irankiai/elektriniai-darbo-irankiai/akumuliatoriniai-irankiai/kiti-akumuliatoriniai-irankiai.html"><span><?php echo __('Kiti akumuliatoriniai įrankiai'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Gyvūnams'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/gyvunu-prekes.html">
                                <span><?php echo __('Gyvūnų prekės'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/gyvunu-prekes/sunims.html"><span><?php echo __('Šunims'); ?></span></a></li>
                            <li><a href="/gyvunu-prekes/katems.html"><span><?php echo __('Katėms'); ?></span></a></li>
                            <li><a href="/gyvunu-prekes/zuvims.html"><span><?php echo __('Žuvims'); ?></span></a></li>
                            <li><a href="/gyvunu-prekes/pauksciams.html"><span><?php echo __('Paukščiams'); ?></span></a></li>
                            <li><a href="/gyvunu-prekes/grauzikams.html"><span><?php echo __('Graužikams'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/ismanieji-namai/ismanus-prietaisai-augintiniams.html">
                                <span><?php echo __('Išmanūs prietaisai augintiniams'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/gyvunu-prekes/transportavimo-priemones-gyvunams.html">
                                <span><?php echo __('Transportavimo priemonės gyvūnams'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/gyvunu-prekes/indai-gyvunams.html">
                                <span><?php echo __('Indai gyvūnams'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/gyvunu-prekes/aromaterapija.html">
                                <span><?php echo __('Aromaterapija'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/gyvunu-prekes/paklotai-gyvunams.html">
                                <span><?php echo __('Paklotai gyvūnams'); ?></span>
                            </a>
                        </h5>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="2444">
                <a class="category-link" href="/zaislai-ir-prekes-vaikams.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/TC-ikonos-outlined_Zaislai-prekes-vaikams.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Žaislai ir prekės vaikams'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="2444" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Žaislai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/lego">
                                <span><?php echo __('LEGO'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/playmobil-zaislai.html">
                                <span><?php echo __('PLAYMOBIL'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai.html">
                                <span><?php echo __('Visi žaislai ❯'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/lauko-zaidimai-ir-zaislai.html">
                                <span><?php echo __('Veiksmo žaidimai ir žaislai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/konstruktoriai.html">
                                <span><?php echo __('Konstruktoriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/lauko-zaidimai-ir-zaislai.html">
                                <span><?php echo __('Lauko žaidimai ir žaislai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/stalo-zaidimai-ir-deliones.html">
                                <span><?php echo __('Stalo žaidimai ir dėlionės'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/lavinamieji-kurybiniai-zaislai.html">
                                <span><?php echo __('Lavinamieji kūrybiniai žaislai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/leles-ir-ju-priedai.html">
                                <span><?php echo __('Lėlės ir jų priedai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/figureles-ir-priedai.html">
                                <span><?php echo __('Figurėlės ir priedai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/mediniai-zaislai.html">
                                <span><?php echo __('Mediniai žaislai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/pliusiniai-zaislai.html">
                                <span><?php echo __('Pliušiniai žaislai'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/veiksmo-zaidimai-ir-zaislai/radijo-bangomis-valdomos-masinos.html">
                                <span><?php echo __('Radijo bangomis valdomos mašinos'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/interaktyvus-zaislai/robotai.html">
                                <span><?php echo __('Robotai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/kiti-zaislai.html">
                                <span><?php echo __('Kiti žaislai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/zaislai-vaikams-iki-3-metu.html">
                                <span><?php echo __('Žаislai vаikams iki 3 metų'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/zaislai/zaislai-vaikams-nuo-3-metu.html">
                                <span><?php echo __('Žаislai vаikams nuo 3 metų'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/interaktyvus-skaitmeninis-gyvunelis-bitzee.html">
                                <span><?php echo __('"BITZEE" interaktyvus gyvūnėlis'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Higiena ir sveikata'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/zaislai-ir-prekes-vaikams/prekes-vaikams/kudikiu-maisto-ruosimo-technika.html">
                                <span><?php echo __('Kūdikių maisto ruošimo technika'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/zaislai-ir-prekes-vaikams/prekes-vaikams/kudikiu-maisto-ruosimo-technika/maisto-garintuvai-ir-trintuvai.html"><span><?php echo __('Maisto garintuvai - trintuvai'); ?></span></a></li>
                            <li><a href="/zaislai-ir-prekes-vaikams/prekes-vaikams/kudikiu-maisto-ruosimo-technika/maisto-sildytuvai.html"><span><?php echo __('Maisto šildytuvai'); ?></span></a></li>
                            <li><a href="/zaislai-ir-prekes-vaikams/prekes-vaikams/kudikiu-maisto-ruosimo-technika/pientraukiai.html"><span><?php echo __('Pientraukiai'); ?></span></a></li>
                            <li><a href="/zaislai-ir-prekes-vaikams/prekes-vaikams/kudikiu-maisto-ruosimo-technika/sterilizatoriai.html"><span><?php echo __('Sterilizatoriai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/zaislai-ir-prekes-vaikams/prekes-vaikams/vaiku-higienos-ir-sveikatos-prekes.html">
                                <span><?php echo __('Vaikų higienos ir sveikatos prekės'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/zaislai-ir-prekes-vaikams/prekes-vaikams/vaiku-higienos-ir-sveikatos-prekes/dantu-sepeteliai-vaikams.html"><span><?php echo __('Dantų šepetėliai vaikams'); ?></span></a></li>
                            <li><a href="/zaislai-ir-prekes-vaikams/prekes-vaikams/vaiku-higienos-ir-sveikatos-prekes/sauskelnes.html"><span><?php echo __('Sauskelnės'); ?></span></a></li>
                            <li><a href="/zaislai-ir-prekes-vaikams/prekes-vaikams/vaiku-higienos-ir-sveikatos-prekes/dregnos-serveteles.html"><span><?php echo __('Drėgnos servetėlės'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Vaikams'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/prekes-vaikams.html">
                                <span><?php echo __('Prekės vaikams'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/zaislai-ir-prekes-vaikams/prekes-vaikams/vaikiski-vezimeliai-ir-priedai.html">
                                <span><?php echo __('Vaikiški vežimėliai ir priedai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/zaislai-ir-prekes-vaikams/prekes-vaikams/vaikiski-vezimeliai-ir-priedai/universalus-vezimeliai.html"><span><?php echo __('Universalūs vežimėliai'); ?></span></a></li>
                        </ul>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="2939">
                <a class="category-link" href="/ismanieji-namai.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/ismanieji-namai_4.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Išmanieji namai. Laisva elektra'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="2939" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Saulės energija'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/ismanieji-namai/saules-energija/nesiojamos-elektros-stoteles.html">
                                <span><?php echo __('Nešiojamos elektros stotelės'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/ismanieji-namai/saules-energija/saules-moduliai-nesiojamoms-elektros-stotelems.html">
                                <span><?php echo __('Saulės moduliai elektros stotelėms'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/saules-elektrines-butui-ir-namams">
                                <span><?php echo __('Saulės elektrinės namams'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/laisva-elektra">
                                <span><?php echo __('Laisva elektra'); ?></span>
                            </a>
                        </h5>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Išmanieji namai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/ismanieji-namai/prietaisai-ismaniesiems-namams.html">
                                <span><?php echo __('Prietaisai išmaniesiems namams'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/ismanieji-asistentai.html"><span><?php echo __('Išmanieji asistentai'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/ismaniosios-koloneles.html"><span><?php echo __('Išmanios kolonėlės'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/ismanusis-apsvietimas.html"><span><?php echo __('Išmanusis apšvietimas'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span></a></li>
                            <li><a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/duru-skambuciai-ir-kameros.html"><span><?php echo __('Durų skambučiai'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/ismaniosios-kameros.html"><span><?php echo __('Kameros'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/ismanieji-valdikliai.html"><span><?php echo __('Įrenginių valdikliai'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/ismaniosios-oru-stoteles.html"><span><?php echo __('Orų stotelės'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/judesio-davikliai.html"><span><?php echo __('Judesio davikliai'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/ismanieji-vazonai.html"><span><?php echo __('Išmanieji vazonai'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/seklos-ismaniems-vazonams.html"><span><?php echo __('Sėklos išmaniam vazonui'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/prietaisai-ismaniesiems-namams/ismanieji-kistukiniai-lizdai.html"><span><?php echo __('Išmanieji kištukiniai lizdai'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Išmanioji buitis'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/ismanieji-namai/ismanioji-buities-technika.html">
                                <span><?php echo __('Išmanioji buities technika'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/buitine-technika/dulkiu-siurbliai-priedai/dulkiu-siurbliai-robotai.html"><span><?php echo __('Siurbliai robotai'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/ismanioji-buities-technika/ismanieji-kavos-aparatai.html"><span><?php echo __('Išmanieji kavos aparatai'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/ismanioji-buities-technika/ismanioji-klimato-kontroles-technika.html"><span><?php echo __('Klimato kontrolės technika'); ?></span></a></li>
                            <li><a href="/namu-apyvokos-prekes/siuksliu-dezes.html"><span><?php echo __('Išmanios šiukšlių dėžės'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Išmanieji prietaisai'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/ismanieji-namai/inovatyvus-prietaisai.html">
                                <span><?php echo __('Inovatyvūs prietaisai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/laisvalaikis/dronai-ir-ju-priedai/dronai.html"><span><?php echo __('Dronai'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span></a></li>
                            <li><a href="/laisvalaikis/elektriniai-paspirtukai.html"><span><?php echo __('Elektriniai paspirtukai'); ?></span></a></li>
                            <li><a href="/sveikata-grozis-sportas/asmenines-higienos-priemones/dantu-sepeteliai.html"><span><?php echo __('Elektriniai dantų šepetėliai'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/inovatyvus-prietaisai/ismaniosios-svarstykles.html"><span><?php echo __('Išmaniosios svarstyklės'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/ismanieji-laikrodziai.html"><span><?php echo __('Išmanieji laikrodžiai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/ismaniosios-apyrankes.html"><span><?php echo __('Išmaniosios apyrankės'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/inovatyvus-prietaisai/daiktu-ieskikliai-ir-aksesuarai.html"><span><?php echo __('Daiktų ieškikliai'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/ismanus-prietaisai-augintiniams.html"><span><?php echo __('Išmanūs prietaisai augintiniams'); ?></span></a></li>
                            <li><a href="/laisvalaikis/echolotai-deeper-fishfinder-ir-garmin.html"><span><?php echo __('Išmanioji žvejyba'); ?></span></a></li>
                            <li><a href="/zaislai-ir-prekes-vaikams/zaislai/interaktyvus-zaislai/ismanieji-zaislai.html"><span><?php echo __('Išmanieji žaislai'); ?></span></a></li>
                            <li><a href="/ismanieji-namai/inovatyvus-prietaisai/prietaisai-levituojantys-ore.html"><span><?php echo __('Levituojantys prietaisai'); ?></span></a></li>
                        </ul>
                    </section>
                </ul>
            </li>
            <li class="category-item" data-desktop_menu_dropdown_item="3807">
                <a class="category-link" href="/automobiliu-prekes.html">
                    <i class="category-icon" style="background-image: url('<?php echo $block->getViewFileUrl('images/icons/automobiliu-prekes.png'); ?>');"></i>
                    <span class="category-name"><?php echo __('Automobilių prekės'); ?></span>
                </a>
                <ul data-desktop_menu_inner_id="3807" class="category-submenu">
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Vaizdo ir garso įranga'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/automobiliu-prekes/auto-registratoriai.html">
                                <span><?php echo __('Vaizdo registratoriai'); ?></span>
                            </a>
                        </h5>
                        <h5 class="submenu-title">
                            <a href="/automobiliu-prekes/navigacijos-iranga.html">
                                <span><?php echo __('Navigacijos įranga'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/automobiliu-prekes/navigacijos-iranga/navigacijos-gps.html"><span><?php echo __('GPS navigacijos'); ?></span></a></li>
                            <li><a href="/automobiliu-prekes/navigacijos-iranga/navigaciju-priedai.html"><span><?php echo __('Navigacijų priedai'); ?></span></a></li>
                        </ul>
                        <h5 class="submenu-title submenu-highlighted">
                            <a href="/automobiliu-prekes/auto-aparatura.html">
                                <span><?php echo __('Auto garso aparatūra'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/automobiliu-prekes/auto-aparatura/auto-magnetolos.html"><span><?php echo __('Automagnetolos'); ?></span></a></li>
                            <li><a href="/automobiliu-prekes/auto-aparatura/garsiakalbiai.html"><span><?php echo __('Garsiakalbiai'); ?></span></a></li>
                            <li><a href="/automobiliu-prekes/auto-aparatura/stiprintuvai.html"><span><?php echo __('Stiprintuvai'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Prietaisai automobiliui'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/automobiliu-prekes/prietaisai-jusu-auto-priemonei.html">
                                <span><?php echo __('Prietaisai auto priemonei'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/telefonai-navigacijos-auto-iranga/prietaisai-jusu-auto-priemonei/laisvu-ranku-iranga.html"><span><?php echo __('Laisvų rankų įranga'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/prietaisai-jusu-auto-priemonei/alkotesteriai.html"><span><?php echo __('Alkotesteriai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/prietaisai-jusu-auto-priemonei/mobiliuju-ikrovikliai.html"><span><?php echo __('Telefonų įkrovikliai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/mobiliuju-telefonu-priedai-aksesuarai/telefonu-laikikliai.html"><span><?php echo __('Telefonų laikikliai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/prietaisai-jusu-auto-priemonei/auksto-slegio-plovimo-irenginiai.html"><span><?php echo __('Aukšto slėgio plovimo įrenginiai'); ?></span></a></li>
                            <li><a href="/telefonai-navigacijos-auto-iranga/prietaisai-jusu-auto-priemonei/fm-moduliatoriai.html"><span><?php echo __('FM moduliatoriai'); ?></span></a></li>
                        </ul>
                    </section>
                    <section class="submenu-section">
                        <h4 class="submenu-section-title"><?php echo __('Elektromobilių įkrovimui'); ?></h4>
                        <hr class="submenu-hr">
                        <h5 class="submenu-title">
                            <a href="/elektromobiliu-ikrovimo-sprendimai">
                                <span><?php echo __('Elektromobilių įkrovimo sprendimai'); ?></span>
                            </a>
                        </h5>
                        <ul class="submenu-child-list">
                            <li><a href="/automobiliu-prekes/elektromobiliu-ikrovimo-iranga/elektromobiliu-ikrovimo-stoteles-namams.html"><span><?php echo __('Įkrovimo stotelės namams'); ?><span class="new-badge"><?php echo __(' Nauja!'); ?></span></span></a></li>
                            <li><a href="/automobiliu-prekes/elektromobiliu-ikrovimo-iranga/elektromobiliu-ikrovimo-stoteles-viesam-naudojimui.html"><span><?php echo __('Įkrovimo stotelės viešam naudojimui'); ?></span></a></li>
                            <li><a href="/automobiliu-prekes/elektromobiliu-ikrovimo-iranga/nesiojami-elektromobiliu-ikrovikliai.html"><span><?php echo __('Nešiojami elektromobilių įkrovikliai'); ?></span></a></li>
                            <li><a href="/automobiliu-prekes/elektromobiliu-ikrovimo-iranga/elektromobiliu-ikrovikliu-priedai.html"><span><?php echo __('Elektromobilių įkroviklių priedai'); ?></span></a></li>
                            <li><a href="/automobiliu-prekes/elektromobiliu-ikrovimo-iranga/elektromobiliu-ikrovikliu-adapteriai.html"><span><?php echo __('Elektromobilių įkroviklių adapteriai'); ?></span></a></li>
                            <li><a href="/automobiliu-prekes/elektromobiliu-ikrovimo-iranga/elektromobiliu-ikrovikliu-laidai.html"><span><?php echo __('Elektromobilių įkroviklių laidai'); ?></span></a></li>
                        </ul>
                    </section>
                </ul>
            </li>
        </ul>
    </div>
</div>
