<div class="main-header">
    <div>
        <div class="main-header-logo">
            <?php echo $block->getChildHtml('topocentras.logo'); ?>
        </div>
        <div class="main-header-search">
            <?php echo $block->getChildHtml('top.search'); ?>
        </div>
        <div class="main-header-actions">
            <a href="<?php echo $block->getUrl('wishlist'); ?>">♥</a>
            <a href="<?php echo $block->getUrl('checkout/cart'); ?>">🛒 Cart</a>
        </div>
    </div>
</div>
