<div class="main-header">
    <div>
        <div class="main-header-logo">
            <?php echo $block->getChildHtml('logo'); ?>
        </div>
        <div class="main-header-search">
            <form action="<?php echo $block->getUrl('catalogsearch/result'); ?>" method="get">
                <input type="text" 
                       name="q" 
                       placeholder="<?php echo __('Ieškokite prekės, kategorijos...'); ?>" 
                       maxlength="128">
                <button type="submit">
                    <img src="<?php echo $block->getViewFileUrl('images/icons/header/search.svg'); ?>" alt="<?php echo __('Ieškoti'); ?>">
                </button>
            </form>
        </div>
        <div class="main-header-actions">
            <a href="<?php echo $block->getUrl('wishlist'); ?>">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg>
            </a>
            <?php echo $block->getChildHtml('minicart'); ?>
        </div>
    </div>
</div>
