<nav class="navigation-bar">
    <div>
        <ul class="navigation-menu">
            <li><a href="#">☰ <?= __('Prekių katalogas') ?></a></li>
            <li><a href="#">🔥 <?= __('Akcijos ir pasiūlymai') ?></a></li>
            <li><a href="#">🍎 <?= __('Apple parduotuvė') ?></a></li>
            <li><a href="#">🔧 <?= __('Paslaugos') ?></a></li>
            <li><a href="#">🏷️ <?= __('Prekės į minusą') ?></a></li>
            <li><a href="#">⭐ <?= __('Topo Klubo pasiūlymai') ?></a></li>
            <li><a href="#">🎁 <?= __('Dovanų kuponas') ?></a></li>
        </ul>
    </div>
</nav>
