<nav class="navigation-bar">
    <div>
        <ul class="navigation-menu">
            <li class="first-item"><a href="#"><img src="<?= $block->getViewFileUrl('images/icons/nav/1.svg') ?>" alt=""> <?= __('Prekių katalogas') ?></a></li>
            <li><a href="#"><img src="<?= $block->getViewFileUrl('images/icons/nav/2.webp') ?>" alt=""> <?= __('Akcijos ir pasiūlymai') ?></a></li>
            <li><a href="#"><img src="<?= $block->getViewFileUrl('images/icons/nav/3.png') ?>" alt=""> <?= __('Apple parduotuvė') ?></a></li>
            <li><a href="#"><img src="<?= $block->getViewFileUrl('images/icons/nav/4.png') ?>" alt=""> <?= __('Paslaugos') ?></a></li>
            <li><a href="#"><img src="<?= $block->getViewFileUrl('images/icons/nav/5.svg') ?>" alt=""> <?= __('Prekės į minusą') ?></a></li>
            <li><a href="#"><img src="<?= $block->getViewFileUrl('images/icons/nav/6.png') ?>" alt=""> <?= __('Topo Klubo pasiūlymai') ?></a></li>
            <li><a href="#"><img src="<?= $block->getViewFileUrl('images/icons/nav/7.svg') ?>" alt=""> <?= __('Dovanų kuponas') ?></a></li>
        </ul>
    </div>
</nav>
