<div class="topbar">
    <div>
        <div>
            <a href="#">
                <img src="<?php echo $block->getViewFileUrl('images/icons/topbar/1.svg'); ?>" alt="Parduotuvės">
                <p class="topbar-link">Parduotuvės</p>
            </a>
            <a href="#">
                <img src="<?php echo $block->getViewFileUrl('images/icons/topbar/2.svg'); ?>" alt="Verslui">
                <p class="topbar-link">Verslui</p>
            </a>
            <span>
                <img src="<?php echo $block->getViewFileUrl('images/icons/topbar/3.svg'); ?>" alt="+370 660 00200">
                +370 660 00200
            </span>
            <span>I - V 8:00 - 22:00 | VI - VII 9:00 - 17:00</span>
        </div>
        <div>
            <a href="#">
                <img src="<?php echo $block->getViewFileUrl('images/icons/topbar/4.svg'); ?>" alt="Užsakymo sekimas">
                <p class="topbar-link">Užsakymo sekimas</p>
            </a>
            <a href="/customer/account">
                <img src="<?php echo $block->getViewFileUrl('images/icons/topbar/5.svg'); ?>" alt="Log in">
                <p class="topbar-link">Log in</p>
            </a>
        </div>
    </div>
</div>
