<div class="topbar">
    <div>
        <div>
            <a href="#">
                <img src="<?php echo $block->getViewFileUrl('images/icons/topbar/1.svg'); ?>" alt="<?= __('Parduotuvės') ?>">
                <p class="topbar-link"><?= __('Parduotuvės') ?></p>
            </a>
            <a href="#">
                <img src="<?php echo $block->getViewFileUrl('images/icons/topbar/2.svg'); ?>" alt="<?= __('Verslui') ?>">
                <p class="topbar-link"><?= __('Verslui') ?></p>
            </a>
            <span>
                <img src="<?php echo $block->getViewFileUrl('images/icons/topbar/3.svg'); ?>" alt="+370 660 00200">
                +370 660 00200
            </span>
            <span><?= __('I - V 8:00 - 22:00 | VI - VII 9:00 - 17:00') ?></span>
        </div>
        <div>
            <a href="#">
                <img src="<?php echo $block->getViewFileUrl('images/icons/topbar/4.svg'); ?>" alt="<?= __('Užsakymo sekimas') ?>">
                <p class="topbar-link"><?= __('Užsakymo sekimas') ?></p>
            </a>
            <a href="/customer/account">
                <img src="<?php echo $block->getViewFileUrl('images/icons/topbar/5.svg'); ?>" alt="<?= __('Prisijungti') ?>">
                <p class="topbar-link"><?= __('Prisijungti') ?></p>
            </a>
        </div>
    </div>
</div>
